---
 - name: install build tool bazel - dependencies
   become: yes
   apt: name={{ item }} state=latest
   with_items:
    - openjdk-8-jdk

 - name: install build tool bazel - add repository key
   become: yes
   apt_key: url='https://bazel.build/bazel-release.pub.gpg'

 - name: install build tool bazel - add repository
   become: yes
   apt_repository: repo="deb http://storage.googleapis.com/bazel-apt stable jdk1.8"

 - name: install build tool bazel
   become: yes
   apt: name={{ item }} state=latest
   with_items:
    - bazel

 - name: install tensorflow build dependencies
   become: yes
   apt: name={{ item }} state=latest
   with_items:
    - python3-numpy
    - python3-dev
    - python3-pip
    - python3-wheel
