---

  - name: install python 3 and virtualenv
    become: true
    apt: name={{ item }} state=latest
    with_items:
      - python3-pip
      - python3-dev
      - python-virtualenv

  - name: install tensorflow using pip
    pip:
      name: tensorflow
      state: latest
      virtualenv: "{{ tensorflow_virtualenv_target_path }}"
      virtualenv_python: python3
