---

  - name: install python 3 and virtualenv
    become: true
    apt: name={{ item }} state=latest
    with_items:
      - python3-pip
      - python3-dev
      - python-virtualenv

  - name: install tensorflow and common libraries using pip
    pip:
      name: "{{ item }}"
      state: latest
      virtualenv: "{{ tensorflow_virtualenv_target_path }}"
      virtualenv_python: python3
    with_items:
      - tensorflow
      - pandas
